name: cos_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  auto_route: ^10.0.1
  flutter_svg: ^2.0.17
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
   - assets/svg/
